services:
    nginx:
        build:
            context: ./build/nginx
            dockerfile: Dockerfile
        volumes:
            - ./app/:/var/www/app/
        ports:
            - "127.0.0.3:80:80"
        networks:
            - recipe
        depends_on:
            - php
            - mysql
    php:
        build:
            context: ./build/php
            dockerfile: Dockerfile
        environment:
            - ./app/.env.local
        volumes:
            - ./app/:/var/www/app/
        networks:
            - recipe
        depends_on:
            - mysql
    mysql:
        build:
            context: ./build/mysql
            dockerfile: Dockerfile
        env_file:
            - ./build/mysql/.env
        ports:
            - "127.0.0.3:3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - recipe

networks:
    recipe: ~
